[package]
name = "nxbft-tee-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enclave-result = { workspace = true }
bincode = "1.3"
nxbft-base = { workspace = true }
thiserror = "1"
