[package]
name = "abcperf-abcwrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tokio = { workspace = true }
trait-alias-macro = { workspace = true }
shared-ids = { workspace = true }
abcperf = { workspace = true }
