[package]
name = "id-set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared-ids = { workspace = true }
serde = "1"
bit-set = { version = "0.8.0", features = ["serde"] }
