[package]
name = "remote-attestation"
version = "1.0.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
uuid = { version = "1.0.0", default-features = false, features = ["v4"] }

[build-dependencies]
rust-sgx-sdk-build-helper = { workspace = true }
